title: Fix It Together
remote_theme: just-the-docs/just-the-docs
mermaid:
  version: "10.9.0"
callouts:
  tip:
    title: ğŸ¤ Tip
    color: purple
  info:
    title: â„¹ï¸ Info
    color: blue
  attention:
    title: â• Attention
    color: yellow
  download:
    title: ğŸ’¾ Download
    color: grey-dk

# Quelle: https://github.com/hwrberlin/fswd-app/blob/main/docs/_config.yml (Zugriff am 11.06.2025)